version: '3.0'

services:
  mongodb-1:
    image: mongo:latest
    container_name: mongodb-1
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ammfat
      MONGO_INITDB_ROOT_PASSWORD: ammfat
      MONGO_INITDB_DATABASE: admin
    networks:
      - mongodb-net
      
networks:
  mongodb-net:
    name: mongodb-net
    driver: bridge