version: '3.0'

services:
  mongodb-1:
    image: mongo:latest
    container_name: mongodb-1
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ammfat
      MONGO_INITDB_ROOT_PASSWORD: ammfat
      MONGO_INITDB_DATABASE: admin
    volumes:
      - "./data-mongo-1:/data/db"
  mongodb-2:
    image: mongo:latest
    container_name: mongodb-2
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ammfat
      MONGO_INITDB_ROOT_PASSWORD: ammfat
      MONGO_INITDB_DATABASE: admin
    volumes:
      - type: bind
        source: "./data-mongo-2"
        target: "/data/db"
        read_only: false